Document TypeScript requirements
Without setting moduleResolution to `node16` or `nodenext`, the following
error may occur:
  Your configFile is invalid: <...>/node_modules/@unflakable/cypress-plugin/dist/config-wrapper.mjs

  It threw an error when required, check the stack trace below:

  Error: Cannot find module 'file://<...>/node_modules/@unflakable/cypress-plugin/dist/config-wrapper.mjs'
  Require stack:
  - <...>/packages/server/lib/plugins/child/run_require_async_child.js
  - <...>/packages/server/lib/plugins/child/require_async_child.js

For some reason, this error doesn't seem to happen on Linux, or at least not
in the `cypress/browsers:node16.16.0-chrome105-ff104-edge` Docker container.